configs = {
    "dataset_path": "/hdd/repos/datasets/VOC",
    "dataset_name": "VOCSegmentation",
    "output_path": "./output",
    "project_name": "Coding_Task_2",
    "experiment_name": "deeplabv3plus_resnet50",
    "project_exist_ok": False,
    "num_classes": 21,  # if incorrect, it will be autocorrected
    "model_name": "deeplabv3plus_resnet50",  # deeplabv3plus_resnet50, deeplabv3plus_resnet32
    "epochs": 50,
    "batch_size": 4,
    "val_batch_size": 1,
    "lr": 0.01,
    "lr_policy": "poly",
    "step_size": 10000,
    "model_save_interval": 4,
    "val_interval": 1,
    "save_val_results": True,
    "gpu_id": 0,
    "num_workers": 2,
    "random_seed": 42,
    "crop_size": 513,
    "crop_val": False,
    "enable_vis": True,
    "vis_num_samples": 15,
    "separable_conv": False,
    "weight_decay": 1e-4,
    "loss_type": "cross_entropy",
}
